import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import AuthProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Build Pro",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider session={session}>{children}</AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
